### ISSUE TITLE
[Question] How to preserve $SOURCEIP

### ISSUE THREAD

**Issue by irongomme** [wizecore/graylog2-output-syslog#12]
How can i use the syslog output and preserve the $SOURCEIP for the destination syslog-ng ?

**Comment by huksley** [comment]
Hi Jerome!

You must turn off using host as source of tcp packets with messages and use
HOST field instead.
Check this out:
https://groups.google.com/forum/#!topic/enterprise-log-search-and-archive/D7A05VKZzz0

29 Ноя 2016 г. 18:44 пользователь "Jérôme" <notifications@github.com>
написал:

**Comment by huksley** [comment]
Closed due to inactivity. Open new issue if you need help.
