### ISSUE TITLE
Plugin does not show proper version number

### ISSUE THREAD

**Issue by ralfbergs** [wizecore/graylog2-output-syslog#15]
In System > Nodes there is a section `Installed plugins` that shows all plugins which are installed in Graylog, and their corresponding version numbers.

For this plugin version `1.0.0` is displayed, even though I installed version 2.1.1 from the [available releases](https://github.com/wizecore/graylog2-output-syslog/releases) page.

**Comment by huksley** [comment]
Which version of Graylog do you use?

**Comment by ralfbergs** [comment]
Graylog 2.1.2+50e449a

**Comment by huksley** [comment]
Fixed by https://github.com/wizecore/graylog2-output-syslog/commit/95245077dc24e8903349a990c7cdb865134a21a3

**Comment by ralfbergs** [comment]
Thanks very much!
