### ISSUE TITLE
Message format "cef" broken

### ISSUE THREAD

**Issue by ralfbergs** [wizecore/graylog2-output-syslog#17]
I created an output with protocol `tcp` and message format `cef`. No output was sent to the destination. When I changed to format `structured`, data _was_ sent.

This is about release 2.1.1 of the plugin.

**Comment by huksley** [comment]
Hi Ralf. CEF format is really experimental as I don`t have access to ArcSight to validate format is correct.

If you will assist in testing, I can try to improve it.

**Comment by ralfbergs** [comment]
Hi Ruslan. We do have ArcSight, but I'm currently not in a position to test. I just chose CEF because I'm pretty clueless about these formats, and thought the "most advanced" format is the best to choose.

In the future we need to send to one ArcSight connector, then I can revisit CEF.

**Comment by huksley** [comment]
Then I suggest you to use structured format.
It should work fine with both arcsight and syslog and provide extended (fields) metadata about events.

If you will have ability to test CEF with ArcSite then I will be happy to fix CEF format.

**Comment by ralfbergs** [comment]
"Structured" is indeed what I'm using now, it's working fine. Thank you.
