### ISSUE TITLE
CEF | No packet sended

### ISSUE THREAD

**Issue by TenGbps** [wizecore/graylog2-output-syslog#19]
Hello, in CEF on graylog 2.3.0, no packet is sended by the graylog server.

CEF : https://kc.mcafee.com/resources/sites/MCAFEE/content/live/CORP_KNOWLEDGEBASE/78000/KB78712/en_US/CEF_White_Paper_20100722.pdf

Tell me if i can help you to debug with my ArcSight

Thanks

**Comment by huksley** [comment]
Hi.
Have you used release JAR or build yourself?

**Comment by huksley** [comment]
Yes. There was CEF support only in 1.3-final branch.
Ported to master and released new JAR. Can you try it?
Ready to fix any quirks and bugs and implement proper ARCSight support.

**Comment by TenGbps** [comment]
Thanks you mutch for you fast reply.
So you need to change some code.

So exemple of forcepoint log directy in CEF and sended by your plugins

```
<6>CEF:0|FORCEPOINT|Firewall|unknown|70021|Connection_Closed|0|in=0 out=0 app=App rt=Sep 06 2017 10:10:00 deviceFacility=Packet filter deviceInboundInterface=1 proto=6 dpt=80 spt=12345 dst=10.11.12.13 src=10.13.12.11 dvchost=10.0.0.1 dvc=10.0.0.1 deviceExternalId=Node1 cs1Label=RuleId cs1=12345.1 cs2Label=NatRuleId cs2=12345.1
<14>Sep  6 10:10:00 159.8.73.44 - -  CEF:0|ArcSight|Logger|5.0.0.5355.2|log:1|"2017-09-06 10:10:00","116459290","10.0.0.1","Packet filter","Notification",,"Permit","10.11.12.13","10.13.12.11","App",
```

**Comment by huksley** [comment]
Please check new release
https://github.com/wizecore/graylog2-output-syslog/releases/tag/2.1.1b

For now I don`t know how to send actual Graylog server version - using fixed 2.1.1.
I`ll figure it out later.

**Comment by TenGbps** [comment]
In good way ;)

`<14>CEF:0|Graylog|graylog-output-syslog:cefsender|2.1.1|log:1|"2017-09-06 12:33:45","118321184","3.3.3.3","Packet filt........................|6|cs3=Clichy cs2=N/A dst=2.2.2.2 cs5=FR cs4=FR gl2_remote_ip=6.6.6.6 gl2_remote_port=53252 cs1Label=PacketFlags cs4Label=Source Country Name source=3.3.3.3 gl2_source_input=59a034791e40e5d502c48dd4 dvc=3.3.3.3 act=Permit cs3Label=Destination City Name dvchost=test.test gl2_source_node=a0000005-0005-0000-abcd-000000000000 timestamp=2017-09-06T10:33:46.484Z cs5Label=Destination Country Name in=0 src=1.1.1.1 dpt=52227 spt=3011 proto=TCP _id=0000-000-000-000 cs2Label=Source City Name gl2_original_timestamp=2017-09-06 12:33:45`

`<x>CEF:0|Device Vendor|Device Product|Device Version|Signature ID|Name|Severity|.......`

Name contant the full message, can you replace it by the messageid(_id) ?

**Comment by huksley** [comment]
I`dont known generic way to reduce Name, here is from the spec:

```bash
Name is a string representing a human-readable and understandable description of the event. The
event name should not contain information that is specifically mentioned in other fields. For example:
"Port scan from 10.0.0.1 targeting 20.1.1.1" is not a good event name. It should be: "Port scan". The other
information is redundant and can be picked up from the other fields.
```

However, I don`t include message or full_message fields in the Extension so
Name is seems to be most suitable place to write.

There is probably a need for configuration for example to make Name be a composition of other fields. Plus fields might need renaming to suit 'CEF Key Names For Event Producers'

**Comment by TenGbps** [comment]
Maybe the short_message is better for name space.

The plugins work ![arcsght](https://user-images.githubusercontent.com/30792994/30108344-435b057e-9302-11e7-8a1a-acfa2510fcf3.jpg)

**Comment by huksley** [comment]
What about these standard CEF extension key names?

  * **externalId** -  The ID used by an originating device. They are usually increasing numbers, associated with events.
  * **msg** - An arbitrary message giving more details about the event. Multi-line entries can be produced by using \n as the newline separator.

**Comment by TenGbps** [comment]
In a active directory he look like this
![capture](https://user-images.githubusercontent.com/30792994/30109332-47601494-9306-11e7-9464-4ed13108498e.JPG)

**Comment by TenGbps** [comment]
Name is fully indexed into ARCSight, better to put fixed value instead of put full message.

**Comment by huksley** [comment]
Check the updated documentation:
https://github.com/wizecore/graylog2-output-syslog/blob/master/README.md#cef-format-handling

**Comment by TenGbps** [comment]
Thanks for you work !
