### ISSUE TITLE
Working with GrayLog 2.4.3 ?

### ISSUE THREAD

**Issue by tristanlepachyderme** [wizecore/graylog2-output-syslog#21]
Hi,

Once the plug-in dropped into the directory and graylog-server restarted, nothing changes in the gui and the pug-in doesn't appear in the installed plug-in section of the System/Node page.

My Java version 
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

Can you help me ?

Thanks !

**Comment by huksley** [comment]
Pls try new JAR in releases
https://github.com/wizecore/graylog2-output-syslog/releases

**Comment by tristanlepachyderme** [comment]
Hi !
I did the update to 2.4.5 of Graylog, re downloaded the last release and place it in the plugin directory.
It still not shows in the plug in list after a restart :/

**Comment by tristanlepachyderme** [comment]
It works !
