### ISSUE TITLE
Will it work on 2.4.4

### ISSUE THREAD

**Issue by latheefp** [wizecore/graylog2-output-syslog#23]
i tried to use this plugin on graylog 2.4.4, but not visible in plugin page of web after restarting graylog server.  is there any compatibility issue?

**Comment by huksley** [comment]
Hello! 
Have you used JAR or tried to build it by yourself?
Can you please try to rebuilt it using new version of dependency in pom.xml?

**Comment by huksley** [comment]
Pls try new JAR in releases
https://github.com/wizecore/graylog2-output-syslog/releases
