### ISSUE TITLE
plugin not available in configuration and not forwarding the message.

### ISSUE THREAD

**Issue by latheefp** [wizecore/graylog2-output-syslog#24]
This plugin is not visible in configuration page of graylog. My graylog version is Graylog 2.4.4+4659dbe on eecsaruh6hor182 (Oracle Corporation 1.8.0_172 on Linux 4.4.0-121-generic)

![image](https://user-images.githubusercontent.com/6326885/44725733-c33fcc80-aade-11e8-8ce1-e6cb4588126e.png)

However, i can see it under output (in system /input out put menu)

![image](https://user-images.githubusercontent.com/6326885/44725851-0ef27600-aadf-11e8-872d-9f1e820805bd.png)

When i do a snoop in servers end also, i see no traffic passing to archsight.
![image](https://user-images.githubusercontent.com/6326885/44725906-30ebf880-aadf-11e8-8a92-8e15dba81b6a.png)

**Comment by huksley** [comment]
Configuration - yes,  is some new page and I need to check how to register plugin in that.

Can you attach log? Or look for specific lines related to *wizecore* or Syslog* and add these to this issue.
Thanks

**Comment by latheefp** [comment]
This is the logs...

root@eecsaruh6hor182:/var/log/graylog/server# grep wizecore current
2018-08-28_11:19:40.39923 INFO  [CmdLineTool] Loaded plugin: SyslogOutputPlugin 1.0.0 [com.wizecore.graylog2.plugin.SyslogOutput]
2018-08-28_11:30:22.95061 INFO  [CmdLineTool] Loaded plugin: SyslogOutputPlugin 1.0.0 [com.wizecore.graylog2.plugin.SyslogOutput]
2018-08-28_11:32:06.63050 INFO  [CmdLineTool] Loaded plugin: SyslogOutputPlugin 1.0.0 [com.wizecore.graylog2.plugin.SyslogOutput]
2018-08-28_12:01:37.85000 INFO  [CmdLineTool] Loaded plugin: SyslogOutputPlugin 1.0.0 [com.wizecore.graylog2.plugin.SyslogOutput]

**Comment by latheefp** [comment]
[current.zip](https://github.com/wizecore/graylog2-output-syslog/files/2331504/current.zip)
find the attached logs (current)

**Comment by latheefp** [comment]
Thanks, its fixed after I assign the stream to this output rules....
![image](https://user-images.githubusercontent.com/6326885/44778520-dbb6f200-ab85-11e8-9221-f8f42686a1a4.png)
