### ISSUE TITLE
UTF-8 support - rfc5424

### ISSUE THREAD

**Issue by adamsh25** [wizecore/graylog2-output-syslog#25]
Hi,

I have issues with UTF-8 support, syslog messages with rfc5424 must contain the (BOM) prefix: 
" If a syslog application encodes MSG in UTF-8, the string MUST start 
with the Unicode byte order mask (BOM), which for UTF-8 is ABNF 
%xEF.BB.BF. The syslog application MUST encode in the "shortest 
form" and MAY use any valid UTF-8 sequence."

https://tools.ietf.org/html/rfc5424

f.g the German letter won't be supported - because the message data will be decoded to ASCII and not to UTF-8, exploring Wireshark packet sent with this plugin output stream, will result in a message that do not have the (BOM) prefix.

Thank you, 
Adam.

**Comment by adamsh25** [comment]
Thank you for your response, 
I think the second option is the best, just add a combo box that will let us decide the encoding or a check box for BOM header - default false is ok.

**Comment by huksley** [comment]
@adamsh25 I implemented BOM support in branch `utf8`
Could you check is it working in your environment? Thank you!

https://github.com/wizecore/graylog2-output-syslog/pull/37

**Comment by huksley** [comment]
Merged #37 and fixed this
