### ISSUE TITLE
Graylog 3 support?

### ISSUE THREAD

**Issue by ml-cms** [wizecore/graylog2-output-syslog#29]
will it work in graylog 3?

**Comment by huksley** [comment]
Hi!
Haven`t tried to run it yet in Graylog 3, but AFAIK there are no big changes in plugin/syslog4j in graylog 3.0
so it should work. How about you give it a go and report if there is any errors/not-working?

**Comment by huksley** [comment]
Yes it works, just checked. Thanks.

**Comment by jgallucci32** [comment]
I am unable to get it to work with Graylog 3.0. I do not see the option in "Select Output Type" when launching a new output. I did the following to install the plugin:
* Downoaded the latest release (graylog-output-syslog-2.4.5.jar)
* Added release to the the `/usr/share/graylog-server/plugin` directory
* Restarted Graylog server with `systemctl restart graylog`

Install details:
* Graylog 3.0.0+db6cf59 on syslog.domain.local (Oracle Corporation 1.8.0_191 on Linux 3.10.0-957.1.3.el7.x86_64)
* Followed CentOS installation instructions on a system running RHEL 7

**Comment by jgallucci32** [comment]
Disregard my previous comment. The download of the .jar file was corrupt. Using the correct .jar file and the steps above I can confirm it is working on Graylog 3.0
