### ISSUE TITLE
Messages are truncated after 226 bytes

### ISSUE THREAD

**Issue by mgoritzk** [wizecore/graylog2-output-syslog#3]
Messages are truncated after 226 bytes and " (...)" is added to the message to indicate that the message was truncated.

It would be nice if messages up to 16 k (default buffer size of rsyslog) would be handled untouched. Maybe it's a good idea to make such a configuration controled by parameters.

**Comment by mgoritzk** [comment]
I forgot the used Graylog2 version: it's 1.3.

**Comment by huksley** [comment]
How do you configure syslog output instance? Please specify values for parameters:
- protocol
- host
- port
- format

**Comment by mgoritzk** [comment]
Configuration:

port: 20005
protocol: tcp
host: xxx-syslog0-prod.yyy.zz.metro.io
format: full
