### ISSUE TITLE
log problem sent parsed

### ISSUE THREAD

**Issue by MLG-ARTE** [wizecore/graylog2-output-syslog#41]
Hello, 
we used the Syslog and ArcSight output plugin 2.5.x, 3.0.0 compatible to send windows logs from our Graylog server to our siem but the sent log is cut, the Qradar does not recover the entire log, can you help, please? We have some example

Thank you

**Comment by TiNico22** [comment]
The problem seems to be related to Nxlog and his ShortMessageLength directive which impact the message length.
Pending pull request related to this topic for readme.md to deal with this common mistake.

**Comment by MLG-ARTE** [comment]
Hi, 

Indeed, that's it

Thanks

**Comment by huksley** [comment]
Hi, is this issue resolved? I merged PR

**Comment by TiNico22** [comment]
Yes, you can close it. 
The solution in the PR was implemented and solved the issue
