### ISSUE TITLE
Problem with output in graylog 4.2.5

### ISSUE THREAD

**Issue by dcantos1** [wizecore/graylog2-output-syslog#51]
I have configured a log output in the graylog, then I capture the configuration and send it to a syslog server in this case to Wazuh but I do not receive anything if I perform a TCPDUMP, the connectivity is in the same internal network, I do not have any port blocked because I already checked it.

![imagen](https://user-images.githubusercontent.com/80493416/151979991-0c36eccc-c435-4abe-9592-a8fcf86ee11e.png)

Additionally, I changed it to various types, for example, full, structured and I still do not receive anything, I attach an image of the tcpdump with the IP of the graylog.
![imagen](https://user-images.githubusercontent.com/80493416/151980145-30b663d2-1df8-470d-8553-3713bc98182d.png)

helpme please!

**Comment by huksley** [comment]
Hi, could you check you added output to some stream. Output will work only if you add it to specific stream or to "All events stream"
