### ISSUE TITLE
Plugin logs to /var/log/message instead of graylog logfile

### ISSUE THREAD

**Issue by 1tft** [wizecore/graylog2-output-syslog#54]
Hello, currently we see at our local syslog _/var/log/messages_ errors produced by graylog2-output-syslog plugin like: 
_Aug 10 12:28:57 HOSTNAME graylog-server[2107]: INFO <14>1 2022-08-10T12:28:57Z r [...]  [org.graylog2.syslog4j.SyslogRuntimeException: java.net.ConnectException: Connection refused (Connection refused)]_

These messages are correct, because target receiver is down.

I want to stop these messages to be pushed to our local syslog file, but as the plugin uses syslog4j (and not log4j) I dont know where I can manipulate log severity etc. of these (plugin own) logs. Does exist there any way, e.g. set java envirnoment var or sth. like this?

**Comment by huksley** [comment]
Hi, you can take a look at the source code. It logs using standard Java/Graylog facilities, which you can configure, I suppose.
