### ISSUE TITLE
How APP-NAME header is set?

### ISSUE THREAD

**Issue by kondziu95** [wizecore/graylog2-output-syslog#56]
Hello,

I want to change value of APP-NAME header, but always it's put "server" value. It is possible to change that?

**Comment by huksley** [comment]
What is APP-NAME? Could you elaborate? Pull request would be appreciated.

**Comment by kondziu95** [comment]
APP-NAME is header defined in RFC-5424. It is used with structured logs and can be used for application identification. #57
