### ISSUE TITLE
Potential incompatibility with Graylog2 6.x

### ISSUE THREAD

**Issue by digdilem** [wizecore/graylog2-output-syslog#58]
Please note: This is one attempt, but if it's true then we'll probably see others experiencing the same as 6.x was released yesterday.

This plugin has been working perfectly throughout Graylog 4.x and 5.x on Rocky 8/9 and been most useful to us, thank you for your work so far.

Following the Graylog2 6.x upgrade from 5.2.7, graylog-server failed to start.  The [release docs](https://go2docs.graylog.org/current/upgrading_graylog/upgrading_graylog_in_red_hat.htm) indicate no breaking changes, so I assumed it would simply be a case of updating the repo and doing a yum update. 

Following are the graylog logs, which mention `SyslogOutput:         "com.wizecore.graylog2.plugin.SyslogOutput"` making me think this plugin is at fault. Unfortunately, I was under pressure to get graylog back up, so reverted to a snapshot before I could dig deep enough. These logs were copied off the broken server before restoring it. 

I intend to try the update again in a couple of days and will try removing this plugin first.  Will try and remember to update this if that allows graylog to start.

Thank you

```
2024-05-08T11:10:37.398+01:00 ERROR [CmdLineTool] Startup error:
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) [Guice/MissingConstructor]: No injectable constructor for type SyslogOutput.

class SyslogOutput does not have a @Inject annotated constructor or a no-arg constructor.

Requested by:
1  : SyslogOutput.class(SyslogOutput.java:43)
     while locating SyslogOutput
     at SyslogOutput$Factory.create(SyslogOutput.java:271)

Learn more:
  https://github.com/google/guice/wiki/MISSING_CONSTRUCTOR

2) [Guice/MissingImplementation]: No implementation for SyslogOutput$Factory was bound.

Requested by:
1  : Graylog2Module.installOutput(Graylog2Module.java:266)
      \_ installed by: PluginBindings -> SyslogOutputModule

Learn more:
  https://github.com/google/guice/wiki/MISSING_IMPLEMENTATION

2 errors

======================
Full classname legend:
======================
Graylog2Module:       "org.graylog2.plugin.inject.Graylog2Module"
PluginBindings:       "org.graylog2.shared.bindings.PluginBindings"
SyslogOutput:         "com.wizecore.graylog2.plugin.SyslogOutput"
SyslogOutput$Factory: "com.wizecore.graylog2.plugin.SyslogOutput$Factory"
SyslogOutputModule:   "com.wizecore.graylog2.plugin.SyslogOutputModule"
========================

========================
End of classname legend:
========================
```

**Comment by huksley** [comment]
Hi, thank you for your report. Really liked your thank comment! Made my day.

Let me take a look and try to compile it against the latest graylog. Maybe plugin architecture changed in GrayLog 6, I haven't received any updates on this also.

**Comment by huksley** [comment]
@digdilem You are an early bird! I usually upgrade only if it hits a some minor version upgrade after all major release bugs were ironed out.

Please checkout this (lightly tested) release
https://github.com/wizecore/graylog2-output-syslog/releases/tag/v6.0.0

I am especially interest to get report on how SSL works

**Comment by digdilem** [comment]
Many thanks for your prompt attention, @huksley  - a very quick turnaround!

I'll give this a try and let you know - it might not be for a day or two as it's for a production machine. 

Thanks again

**Comment by huksley** [comment]
I am gonna closed it for now. If there is issues with Graylog 6.x plugin - please open new ticket!
