### ISSUE TITLE
The correct version is not displayed after updating the plugin.

### ISSUE THREAD

**Issue by pagudo** [wizecore/graylog2-output-syslog#59]
Hi
I have upgraded the plugin from version 4.2.6 to 6.0.0, but in the "Installed plugins" panel of the only node my environment has, it still shows version 4.2.6.
To update the plugin I have replaced the graylog-output-syslog-4.2.6.jar file with graylog-output-syslog-6.0.0.jar in the "/usr/share/graylog-server/plugin/" folder.

This happens at least with Graylog Open versions 5.2.8 and 6.0.3.

Thanks

**Comment by huksley** [comment]
So, if you have two JARs with different versionand it pickups the older one? I am not sure it can be controlled on plugin level

**Comment by pagudo** [comment]
I'm sorry, but I think I didn't explain it well.

To update the plugin I deleted the file "graylog-output-syslog-4.2.6.jar" and copied the file "graylog-output-syslog-6.0.0.jar" in the folder "/usr/share/graylog-server/plugin/", so I only have the file "graylog-output-syslog-6.0.0.jar" in that folder.

**Comment by huksley** [comment]
Now i got It! I think I forgot to update the version in metadata here https://github.com/wizecore/graylog2-output-syslog/blob/master/src/main/java/com/wizecore/graylog2/plugin/SyslogOutputMetaData.java

Thank you for reporting!
I will fix it later, functionally it should work ok, just the version displayed wrong

**Comment by pagudo** [comment]
Yes, the functionality seems to be correct. It's just a problem with displaying the correct version.
Thanks to you for your quick support and solving the small problem...

**Comment by kontiki99** [comment]
hello, I downloaded the plugin and tried to build it with mvn package, but it fails with error "T E S T S
Running com.wizecore.graylog2.plugin.test.TestFullSender
Tests run: 2, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.107 sec <<< FAILURE!
testMessageTruncation(com.wizecore.graylog2.plugin.test.TestFullSender) Time elapsed: 0.073 sec <<< ERROR!
java.lang.NoClassDefFoundError: com/swrve/ratelimitedlogger/RateLimitedLog
at org.graylog2.plugin.utilities.ratelimitedlog.RateLimitedLogFactory.createRateLimitedLog(RateLimitedLogFactory.java:31)
at org.graylog2.plugin.Message.(Message.java:89)´"  .   
 Any hints please? I admit I am first time maven user.

**Comment by huksley** [comment]
Should be fixed in latest release.
