### ISSUE TITLE
No plugin configuration option available

### ISSUE THREAD

**Issue by madchap** [wizecore/graylog2-output-syslog#6]
Hi,

I can see the output show up in the dropdown box, but there is no input fields to configure it when you want to launch it, except for the name and prefix. Nothing about protocol, host, port or format (it used to work in a previous version, but can't remember which one exactly, maybe a 1.2.x in the days).

I could not really dig into it a whole bunch, but the install is pretty easy, so...

I am running Graylog 1.3.4.

Thanks!

**Comment by madchap** [comment]
I just deployed the 1.3.4 ova on my workstation, I don't have the issue.

My prod systems have been updated over time with the graylog rpms. I will look around to have some debug information if possible.

**Comment by madchap** [comment]
Graylog user thread: https://groups.google.com/forum/#!topic/graylog2/hLRlorTDkMw

**Comment by huksley** [comment]
Hi!
I`ve recently updated plugin with new features, see issue #5. 
I haven`t experienced any issues with configuration.
Do you have an option to do following:

- Remove output from system
- Stop graylog server
- Update jar
- Start again
- Create output (globally)

**Comment by madchap** [comment]
I am sorry about that !!!

(Chose STDOUT instead of syslog)

No issues so far except with my eyes!

**Comment by huksley** [comment]
Ok, no problem! Happy graylogging!
