### ISSUE TITLE
building the plugin with mvn package fails with errors

### ISSUE THREAD

**Issue by kontiki99** [wizecore/graylog2-output-syslog#60]
Hello, I downloaded the plugin and tried to build it with mvn package, but it fails with error "T E S T S
Running com.wizecore.graylog2.plugin.test.TestFullSender
Tests run: 2, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.107 sec <<< FAILURE!
testMessageTruncation(com.wizecore.graylog2.plugin.test.TestFullSender) Time elapsed: 0.073 sec <<< ERROR!
java.lang.NoClassDefFoundError: com/swrve/ratelimitedlogger/RateLimitedLog
at org.graylog2.plugin.utilities.ratelimitedlog.RateLimitedLogFactory.createRateLimitedLog(RateLimitedLogFactory.java:31)
at org.graylog2.plugin.Message.(Message.java:89)´" .
Any hints please? I admit I am first time maven user.

I setu up envirinment on Oracle Linux. I downloaded Java JDK version 17.

**Comment by huksley** [comment]
Try running maven with -DskipTests

**Comment by kontiki99** [comment]
uf, it works now! Thank you so much.

**Comment by huksley** [comment]
Fixed in the latest version.
