### ISSUE TITLE
Forward to QRadar

### ISSUE THREAD

**Issue by zahnd** [wizecore/graylog2-output-syslog#7]
Hi

We're using QRadar as receiver of forwarded messages. Prior to Graylog we used logstash and the messages could be parsed by QRadar. During tests with this plugin we see that parsing isn't possible anymore.

The following message was forwarded by logstash:
`<6>Apr 10 11:03:45 123.123.123.123 LOGSTASH[-]: <132>%ASA-4-106023: Deny tcp src outside:117.7.110.174/56786 dst inside253:xxx.yyy.zzz.vvv/23 by access-group "outside-ingress" [0xd6edd920, 0x0]
`

This one by this plugin with setting "plain":
`<12>Jun 17 13:07:53 123.123.123.123 local0 - Deny tcp src outside:71.6.158.166/34680 dst inside253:xxx.yyy.zzz.vvv/25105 by access-group "aubeinside" [0xb67145c6, 0x0]`

The only difference is that with logstash the header of the original message also has been forwarded and de delimiter between the logstash header and message header is a ":" instead of a "-".

Would it maybe be possible to have another output type which is like "plain" but appends the full original message inclusive header?

Thank you and kind regards, Stefan

**Comment by huksley** [comment]
Hi Stefan!
Sorry but I noticed this issue only now. Is it still relevant?

**Comment by huksley** [comment]
Closing as not relevant.

**Comment by zahnd** [comment]
Hi Huksley

Sorry for the late response. It's actual again :). Would it be a great effort to implement a full_message sender?

Kind regards, Stefan

**Comment by huksley** [comment]
Check this:
https://github.com/wizecore/graylog2-output-syslog#full

As for header there is no such "forwarded" header as we are not forwarding messages.

**Comment by zahnd** [comment]
Hi Huksley

Okay, thank you.
